### ISSUE TITLE
Justlog

### ISSUE THREAD

**Issue by GreenComfyTea** [jammehcow/awesome-twitch-stuff#25]
### Submission checklist

- [X] This item is not on the list
- [X] An issue does not exist for this item (open or closed)

### Tool name

Justlog

### Website/repository URL

https://logs.ivr.fi/

### Category

Chat Applications

### Description

A cloud-based chat logs for picked set of channels.

**Comment by jammehcow** [comment]
Going to close until I get a yes from the owner on including it in the list.

**Comment by GreenComfyTea** [comment]
its under MIT license, you shouldn't be needing the permission to destribute it. 
https://github.com/gempir/justlog/blob/master/LICENSE
